### ISSUE TITLE
Should flights also have time variable

### ISSUE THREAD

**Issue by hadley** [hadley/nycflights13#11]
That combines year, month, day, and dep_time?

**Comment by nicholasjhorton** [comment]
I think that this would be a useful addition.

**Comment by hadley** [comment]
I think I'll call it `datetime`.  This makes things slightly inconsistent because weather has year, month, day, hour, and date, and flights has year, month, day, hour, minute and date time, but I don't think it's possible to do better because of the difference resolutions of the data. (Otherwise you'd be forced to talk about lubridate before using these data to teach joins with dplyr)

**Comment by beanumber** [comment]
How about `dep_timestamp` and `arr_timestamp`?

**Comment by hadley** [comment]
Hmmm, I'm having second (third?) thoughts - about this as there are potential four times you might want to associate with each date: scheduled departure time, actual departure time, scheduled arrival time, scheduled departure date. I'd rather not have four timestamps.

If I was to start from scratch on this dataset, I'd probably have date + four time stamps that represent time as number of seconds from midnight, rather than year + month + day and two timestamps represented as strings. But I'm not sure if I can change now without breaking a lot of example code in the wild.

**Comment by hadley** [comment]
I definitely do need to add `CRSDepTime` and `CRSArrTime` - any suggestions for names? `dep_time_scheduled` and `arr_time_scheduled` are a bit long.

**Comment by nicholasjhorton** [comment]
How about dep_time_sched and arr_time_sched?

Nick

P.S. Perhaps you could include an example in the documentation for "flights" that uses mutate to create a variety of time variables?


> On Jan 4, 2016, at 9:15 AM, Hadley Wickham <notifications@github.com> wrote:
> 
> I definitely do need to add CRSDepTime and CRSArrTime - any suggestions for names? dep_time_scheduled and arr_time_scheduled are a bit long.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by hadley** [comment]
Both good ideas :)

Also I need to make sure that `hour` refers to the scheduled departure time, because when joining to weather, that's the time that's important. (And in fact that will make an interesting challenge: compare the weather at scheduled vs. actual departure times)

**Comment by hadley** [comment]
One other problem to check: if an evening flight is delayed until the next day, does the date refer to scheduled or actual?

**Comment by nicholasjhorton** [comment]
I've always interpreted this as scheduled, since you'll see the actual earlier than the scheduled.  The only issue I can imagine is if the flight was delayed more than 24 hours (but I can't imagine that it happens often).

Nick

> On Jan 4, 2016, at 9:27 AM, Hadley Wickham <notifications@github.com> wrote:
> 
> One other problem to check: if an evening flight is delayed until the next day, does the date refer to scheduled or actual?
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by beanumber** [comment]
Are there performances issues when filtering `year` as a numeric variable as opposed to `lubridate::year(dep_time_sched)`? 

In general I like the idea of storing dates as dates and times as times, but in this particular case I'd be worried about a performance hit. 

[Or maybe you are just talking about *adding* the time variable...]

**Comment by beanumber** [comment]
What about using the DATE and TIME classes separately? Both MySQL and PostgreSQL support these. SQLite doesn't, but it doesn't have time classes anyway, so they would just be stored as text. 

So you could have "date" as YYYY-MM-DD and then "dep_time", "sched_dep_time", "arr_time", and "sched_arr_time" would all be HH:MM:SS. 

We could then drop the "month", "day", "hour", and "minute" columns. 

Also, what happens to red-eyes?

**Comment by beanumber** [comment]
Oh, but R probably doesn't have a TIME class. Would it ruin things to have these as `character`?

**Comment by hadley** [comment]
See the hms package
