### ISSUE TITLE
Check all data frames use factors

### ISSUE THREAD

**Issue by hadley** [hadley/nycflights13#2]
e.g. flights

**Comment by nicholasjhorton** [comment]
dest, origin, carrier, and tailnum are defined as chr in the flights table.

But why make them all factors?  Why not change the "name" variable in the "airlines" table to character?

**Comment by hadley** [comment]
I don't know why I thought this was a good idea anymore :/

**Comment by nicholasjhorton** [comment]
Note that the current setup yields a warning (since airlines uses factors) when you run:

> require(nycflights13)
> sfoflights <- inner_join(filter(flights, dest=="SFO"), airlines)
Joining by: "carrier"
Warning message:
joining character vector and factor, coercing into character vector

**Comment by hadley** [comment]
Oh bummer, thanks for pointing that out.
