### ISSUE TITLE
"Asia/Chongqing" is not an IANA timezone

### ISSUE THREAD

**Issue by bramtayl** [hadley/nycflights13#37]
It's an alias for "Asia/Shanghai"

**Comment by hadley** [comment]
It's in `OlsonNames()`, so I think it's reasonable to keep in here (and I'd prefer not to mess with the original data source if at all possible)

**Comment by bramtayl** [comment]
Ok. Since I've got your attention, you might be interested in https://bramtayl.github.io/LightQuery.jl/latest/
