### ISSUE TITLE
URL broken in data-raw/planes.R

### ISSUE THREAD

**Issue by beanumber** [hadley/nycflights13#6]
On line 3:
```
src <- "http://registry.faa.gov/database/AR062014.zip"
```
This URL does not appear to be a ZIP archive, but instead redirects to (http://www.faa.gov/about/office_org/headquarters_offices/avs/offices/afs/afs700/)
Consequently, it's not possible to re-create the `planes` data frame.

**Comment by beanumber** [comment]
I see what is happening here. It's an un-cacheable URL. Drag.

**Comment by hadley** [comment]
Hmmmm, this is a pain - I tried updating with the latest data ("AR122015.zip"), but that just results in data being dropped. I think that implies this dataset only contains currently registered planes which implies we probably want the data as of December 2013. I have no idea how to get that.

**Comment by ianmcook** [comment]
To see how to fix this, see https://github.com/jrnold/groundcontrol/blob/master/R/planes.R.
