### ISSUE TITLE
query about including both incoming and outgoing flights

### ISSUE THREAD

**Issue by nicholasjhorton** [hadley/nycflights13#8]
I realize that there are serious space limitations on the size of packages on CRAN.  But would it be feasible within those constraints to include both incoming and outgoing flights?  This would allow a whole series of questions to be answer about differences between departures and arrivals at JFK, for example.

**Comment by hadley** [comment]
I think I'm already pushing the limit for file size :/

**Comment by nicholasjhorton** [comment]
I feared as much...
