### ISSUE TITLE
query about including both incoming vs. outgoing flights

### ISSUE THREAD

**Issue by nicholasjhorton** [hadley/nycflights13#9]
Is it feasible to include both incoming and outgoing flights in the nycflights13 package?  I know that large packages are frowned upon by CRAN, but could an exception be made?

Is the problem one of a single large table?  Could the "flights" table be split into two parts (and built together at package installation time)?

This might allow a version of the package on github to include more cities and years without running into the "Github doesn't like files greater than 50MB".

If you have general advice on providing access to larger datasets via R packages hosted on github, I'd be all ears (and suspect that @beanumber and @rpruim would as well!).

**Comment by rpruim** [comment]
I guess I won't send that email I was writing...

**Comment by hadley** [comment]
I think I made it as large as I could without running into CRAN problems :/

**Comment by rpruim** [comment]
What about the idea of exceeding github's single file size limit by have the package combine data from multiple files at install time as a way to deliver data one order of magnitude larger than github would otherwise allow?  Is there any reason that this is a bad idea?

**Comment by hadley** [comment]
It's not the github file size that's the main problem, it's the CRAN file size. It's possible to work around it by downloading datasets after the package is installed, but that would require a decent amount of thinking to make sure it worked in a wide range of situations.

**Comment by beanumber** [comment]
The [airlines](https://github.com/beanumber/airlines) package will do exactly that as soon as I get around to finishing it. But please feel free to take it out for a spin now!

More generally, I'm working on an [etl](https://github.com/beanumber/etl) package that will provide a general framework for having small R packages provide interfaces to medium-sized data sets. Your comments are welcome.

**Comment by nicholasjhorton** [comment]
Ben,

I suspect that we need a version of the airlines package that doesn't require use of a database backend (for smaller medium-sized datasets).

Nick

> On Oct 30, 2015, at 9:48 AM, Ben Baumer <notifications@github.com> wrote:
> 
> The airlines package will do exactly that as soon as I get around to finishing it. But please feel free to take it out for a spin now!
> 
> More generally, I'm working on an etl package that will provide a general framework for having small R packages provide interfaces to medium-sized data sets. Your comments are welcome.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
Box 2239, 31 Quadrangle Dr
Amherst, MA 01002-5000
https://www.amherst.edu/people/facstaff/nhorton

**Comment by beanumber** [comment]
Sure, we could modify things so that you don't have to use the database backend. But then where are you going to store the data? In `.rda` files? In CSVs? I'd worry that this will lead to a "not the right tool for the job" situation, and that if you really want to work with data of this size (dozens of GBs) and structure (relational), that maybe it's not reasonable to think that you are going to get away with this without using a RDBMS.

**Comment by nicholasjhorton** [comment]
I'm thinking a different use case with data on the order of tens of megabytes (current CRAN limit?) to a handful of GB. 

For tens of GB or larger your approach with etl and airlines is the best bet. 

All the best,

Nick

**Comment by beanumber** [comment]
I believe the current CRAN limit is 5 MB.

**Comment by jennybc** [comment]
This solution the @richfitz is working on might qualify as "a decent amount of thinking to make sure it worked in a wide range of situations":

https://github.com/richfitz/datastorr
